// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: dropcheck/v1/control.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DropcheckControl_Session_FullMethodName = "/dropcheck.v1.DropcheckControl/Session"
)

// DropcheckControlClient is the client API for DropcheckControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DropcheckControlClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (DropcheckControl_SessionClient, error)
}

type dropcheckControlClient struct {
	cc grpc.ClientConnInterface
}

func NewDropcheckControlClient(cc grpc.ClientConnInterface) DropcheckControlClient {
	return &dropcheckControlClient{cc}
}

func (c *dropcheckControlClient) Session(ctx context.Context, opts ...grpc.CallOption) (DropcheckControl_SessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &DropcheckControl_ServiceDesc.Streams[0], DropcheckControl_Session_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &dropcheckControlSessionClient{stream}
	return x, nil
}

type DropcheckControl_SessionClient interface {
	Send(*AgentFrame) error
	Recv() (*ControllerFrame, error)
	grpc.ClientStream
}

type dropcheckControlSessionClient struct {
	grpc.ClientStream
}

func (x *dropcheckControlSessionClient) Send(m *AgentFrame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dropcheckControlSessionClient) Recv() (*ControllerFrame, error) {
	m := new(ControllerFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DropcheckControlServer is the server API for DropcheckControl service.
// All implementations must embed UnimplementedDropcheckControlServer
// for forward compatibility
type DropcheckControlServer interface {
	Session(DropcheckControl_SessionServer) error
	mustEmbedUnimplementedDropcheckControlServer()
}

// UnimplementedDropcheckControlServer must be embedded to have forward compatible implementations.
type UnimplementedDropcheckControlServer struct {
}

func (UnimplementedDropcheckControlServer) Session(DropcheckControl_SessionServer) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedDropcheckControlServer) mustEmbedUnimplementedDropcheckControlServer() {}

// UnsafeDropcheckControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DropcheckControlServer will
// result in compilation errors.
type UnsafeDropcheckControlServer interface {
	mustEmbedUnimplementedDropcheckControlServer()
}

func RegisterDropcheckControlServer(s grpc.ServiceRegistrar, srv DropcheckControlServer) {
	s.RegisterService(&DropcheckControl_ServiceDesc, srv)
}

func _DropcheckControl_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DropcheckControlServer).Session(&dropcheckControlSessionServer{stream})
}

type DropcheckControl_SessionServer interface {
	Send(*ControllerFrame) error
	Recv() (*AgentFrame, error)
	grpc.ServerStream
}

type dropcheckControlSessionServer struct {
	grpc.ServerStream
}

func (x *dropcheckControlSessionServer) Send(m *ControllerFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dropcheckControlSessionServer) Recv() (*AgentFrame, error) {
	m := new(AgentFrame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DropcheckControl_ServiceDesc is the grpc.ServiceDesc for DropcheckControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DropcheckControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dropcheck.v1.DropcheckControl",
	HandlerType: (*DropcheckControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _DropcheckControl_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dropcheck/v1/control.proto",
}
